USE datawarehouseanalytics;
drop TABLE adidas_sale;
CREATE TABLE adidas_sale (
Retailer VARCHAR(50),
Retailer_ID INT NOT NULL,
Invoice_Date DATE NOT NULL,
Region VARCHAR(50),
State VARCHAR(50),
City VARCHAR(50),
Product VARCHAR(50),
Price_per_Unit DECIMAL(8, 2) NOT NULL,
Units_Sold DECIMAL (8,2) NOT NULL,
Total_Sales DECIMAL (8,2) NOT NULL,
Operating_Profit DECIMAL (8,2),
Operating_Margin DECIMAL (2,2),
Sales_Method VARCHAR(50)
);

LOAD DATA INFILE "C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\Adidas US Sales Datasets.csv"
INTO TABLE adidas_sale
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES
(Retailer, Retailer_ID, @Invoice_Date, Region, State,
 City, Product, Price_per_Unit, Units_Sold, 
Total_Sales, Operating_Profit, Operating_Margin, Sales_Method)
SET
Invoice_Date =str_to_date(@Invoice_Date, '%m/%d/%Y');
-- Operating_margin = concat(@operating_margin,'','%');
/* Price_per_Unit = REPLACE(REPLACE(@Price_per_Unit, '$', ''),',',''),
Total_Sales = REPLACE( REPLACE(@Total_Sales, '$', ''), ',', ''),
 Operating_Profit = REPLACE(REPLACE(@Operating_Profit, '$', ''), ',', ''),
 Operating_Margin = REPLACE(REPLACE(@Operating_Margin, '$', ''), ',', '') */

-- Data Cleaning
SELECT *
FROM adidas_sale;
SELECT retailer
FROM adidas_sale
WHERE Retailer != TRIM(Retailer);  -- return none. it means the values are all good
-- RETAILER_ID COLUMN
SELECT DISTINCT Retailer_ID
FROM adidas_sale
WHERE Retailer_ID != TRIM(Retailer_ID); -- CORRECT AND CLEAN data

SELECT Product
FROM adidas_sale
WHERE Product != TRIM(Product);

/*. What is the total revenue generated by each product category (e.g., Men's Street 
 Footwear, Women's Apparel)? */
 SELECT 
		product,
        sum(total_sales) total_revenue
FROM adidas_sale
GROUP BY product
ORDER BY sum(total_sales) DESC;
 
 /* Which sales method (In-store vs. Outlet) generates the highest revenue across all 
products? */
 SELECT 
		Sales_Method,
        sum(total_sales) total_revenue
FROM adidas_sale
GROUP BY Sales_Method
ORDER BY sum(total_sales) DESC;

/* What is the average operating margin across all product categories? */
 SELECT 
		Product,
        AVG(Operating_Margin) average_op_mgn,
         CONCAT(ROUND(AVG(Operating_Margin) * 100, 2), '', '%') AS percent_avg_op_mgn
FROM adidas_sale
GROUP BY Product
ORDER BY  AVG(Operating_Margin) DESC;

/* How does the total revenue change across different weeks or months? */
WITH weekly_sale AS (
SELECT 
       extract(week from Invoice_Date) weeklysale,
       SUM(Total_Sales) total_revenue
FROM adidas_sale
GROUP BY  extract(week from Invoice_Date))
, week_lag AS (SELECT ws.weeklysale,
		ws.total_revenue,
        LAG(ws.total_revenue) OVER(ORDER BY  ws.weeklysale) prev_weeklytotal
FROM weekly_sale ws)
SELECT
		weeklysale,
        total_revenue,
        prev_weeklytotal,
        ROUND((total_revenue - prev_weeklytotal) / prev_weeklytotal * 100, 2) WOW_rvnue_chng
FROM week_lag;

-- mom change
 SELECT sale_monthly, 
		 ROUND((monthly_revenue -  coalesce(previous_month_sale, 0)) / previous_month_sale * 100, 2) MOM_change
 FROM(
SELECT
			month(Invoice_Date) sale_monthly,
            SUM(Total_Sales) monthly_revenue,
            lag(coalesce(SUM(Total_Sales), 0)) OVER(ORDER BY month(Invoice_Date)) previous_month_sale
FROM adidas_sale
GROUP BY month(Invoice_Date)
ORDER BY month(Invoice_Date) asc)T;

/* Which region contributes the most to the total sales, and does it align with the highest 
profitability? */
SELECT	 Region,
		COUNT(Total_Sales),
		SUM(Total_Sales) total_sales_per_region,
        SUM(Operating_Profit) Profit_per_region
FROM adidas_sale
GROUP BY region
ORDER BY SUM(Total_Sales) DESC,
        SUM(Operating_Profit) DESC, COUNT(Total_Sales) DESC;
        
/* Are there specific dates or weeks when certain products experienced a significant 
spike or drop in sales? */
-- DAY CHANGE
WITH day_total AS (
SELECT day(Invoice_Date) day_of_week,
		Product,
        SUM(Total_Sales) weeklytotal_sale
FROM adidas_sale
GROUP BY day(Invoice_Date),
		Product)
, lag_day AS (SELECT 
		day_of_week,
		Product,
        weeklytotal_sale,
		LAG(weeklytotal_sale) OVER(PARTITION BY product ORDER BY day_of_week) prev_day_sale
FROM day_total)
SELECT 
		day_of_week,
		Product,
		CONCAT(ROUND((weeklytotal_sale - prev_day_sale) / prev_day_sale * 100, 2),'','%') as DOD_change
FROM lag_day
WHERE prev_day_sale IS NOT NULL;

-- FOR WEEK

WITH week_t AS (SELECT 
		Product,
		week(Invoice_Date, 1) week_of_month,
		SUM(Total_Sales) weekly_sale
FROM adidas_sale
GROUP BY week(Invoice_Date, 1), Product)
, lag_week AS (SELECT
		Product,
		week_of_month,
		weekly_sale,
		LAG(weekly_sale) OVER(PARTITION BY Product ORDER BY week_of_month) previous_week_sale
FROM week_t)
SELECT 
	product,
	week_of_month,
	CONCAT(ROUND((weekly_sale - previous_week_sale) / previous_week_sale * 100, 2),'', '%') WOW_change
FROM lag_week;

-- Which product category has the highest operating profit across both sales methods?
SELECT 
		Product,
		Sales_Method,
		SUM(Operating_Profit) total_profit
FROM adidas_sale
GROUP BY Product, Sales_Method
ORDER BY SUM(Operating_Profit) DESC, Product desc;

-- What is the average profit margin for products sold via In-store vs. Outlet methods?
SELECT Sales_Method,  CONCAT(ROUND(average_profit_margin*100, 2),'','%') percentage_avg_profit
FROM (
SELECT 
		Sales_Method,
		AVG(Operating_Margin) average_profit_margin
FROM adidas_sale
WHERE Sales_Method IN ('In-store', 'outlet')
GROUP BY Sales_Method) T;

-- Which product had the lowest operating margin, and how can this be improved?
SELECT Product,
		Min(Operating_Margin) lowest_operating_margin
FROM adidas_sale
GROUP BY Product
ORDER BY Min(Operating_Margin);

/* What is the total revenue generated from each product in the Men's Footwear 
category */
SELECT
		product,
        SUM(Total_Sales) total_revenue
FROM adidas_sale
WHERE Product IN ('Men''s Street Footwear', 'Men''s Athletic Footwear', 'Men''s Apparel')
GROUP BY product;
/* How does the performance of Women's Athletic Footwear compare to Women's Street 
Footwear in terms of sales and profit? */
SELECT product,
		COUNT(*) total_unit,
		SUM(Total_Sales) total_revenue,
       SUM(Operating_Profit) total_profit
FROM adidas_sale
WHERE product IN ('Women''s Street Footwear', 'Women''s Athletic Footwear')
GROUP BY product;

/* What is the average units sold per day for each product category? */
SELECT 
Invoice_Date,
product,
AVG(Units_Sold) average_unit_sold
FROM adidas_sale
GROUP BY Invoice_Date, product
ORDER BY Invoice_Date ASC
 -- Product asc